using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: Guid("a287fe42-8da0-46cd-9562-9b35274da061")]

[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]
[assembly: InternalsVisibleTo("Abc.Zebus.Directory")]
[assembly: InternalsVisibleTo("Abc.Zebus.Directory.Runner")]
[assembly: InternalsVisibleTo("Abc.Zebus.Directory.Tests")]
[assembly: InternalsVisibleTo("Abc.Zebus.Directory.Cassandra.Tests")]
[assembly: InternalsVisibleTo("Abc.Zebus.Directory.RocksDb.Tests")]
[assembly: InternalsVisibleTo("Abc.Zebus.Testing")]
[assembly: InternalsVisibleTo("Abc.Zebus.Tests")]
[assembly: InternalsVisibleTo("Abc.Zebus.Persistence")]
[assembly: InternalsVisibleTo("Abc.Zebus.Persistence.Tests")]
[assembly: InternalsVisibleTo("Abc.Zebus.Integration")]
[assembly: InternalsVisibleTo("Abc.Zebus.TestTools")]
[assembly: InternalsVisibleTo("Abc.Zebus.PersistenceService.Tests")]
[assembly: InternalsVisibleTo("Abc.Zebus.DirectoryService.Tests")]
[assembly: InternalsVisibleTo("Abc.Zebus.EventSourcing")]
[assembly: InternalsVisibleTo("Abc.Zebus.EventSourcing.Tests")]
[assembly: InternalsVisibleTo("Abc.Zebus.EventSourcing.TestTools")]
[assembly: InternalsVisibleTo("Abc.Zebus.Saga.Tests")]
[assembly: InternalsVisibleTo("Abc.ServiceBus.Monitoring.Tests")]
[assembly: InternalsVisibleTo("Abc.ConfigManagerService.Tests")]

[assembly: InternalsVisibleTo("Abc.Zebus.Persistence")]
[assembly: InternalsVisibleTo("Abc.Zebus.Persistence.CQL")]
[assembly: InternalsVisibleTo("Abc.Zebus.Persistence.CQL.Tests")]
[assembly: InternalsVisibleTo("Abc.Zebus.Persistence.RocksDb")]
[assembly: InternalsVisibleTo("Abc.Zebus.Persistence.RocksDb.Tests")]
