//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyDescription("The Directory service used by Zebus - https://github.com/Abc-Arbitrage/Zebus.Directory")]
[assembly: AssemblyCompany("ABC arbitrage")]
[assembly: AssemblyProduct("Zebus.Directory")]
[assembly: AssemblyVersion("1.3.2")]
[assembly: AssemblyFileVersion("1.3.2")]
[assembly: AssemblyInformationalVersion("1.3.2-beta")]
[assembly: AssemblyCopyright("Copyright © ABC arbitrage 2017")]

